### ISSUE TITLE
mathforces submissions crash the downloader

### ISSUE THREAD

**Issue by krofna** [ISKU/Codeforces-Solutions-Downloader#3] opened 2019-05-17 11:21 UTC
https://codeforces.com/contest/1164

**Comment by ISKU** [comment] 2019-05-19 09:15
Hi @krofna 
Thank you for using this tool.
I have identified the problem with this issue and solved it as follows:

First, you need permission to access the source code of the contest.
Also, the correct source code for the problem can't specify the language.
As a result, for the contest issue, I fixed the code so that it does not download the source code. This problem is classified as a failure.

The issue is resolved in this PR #4
If you have any other good ideas, please let me know.

**Closed as completed** 2019-06-02 09:30 UTC
Labels: bug

**Comment by ISKU** [comment] 2019-06-02 09:37
This issue has been resolved.
If you have any other problems, please open a new issue or reopen this issue.
Thanks.
